name: Update LeetCode Stats

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats and table
        run: |
          EASY=0
          MEDIUM=0
          HARD=0
          TOTAL=0

          echo "| # | Problem | Difficulty | Language |" > table.md
          echo "|---|---------|------------|----------|" >> table.md

          for file in *.java; do
            TOTAL=$((TOTAL+1))

            NAME=$(basename "$file" .java)

            if [[ "$NAME" =~ ^1|^2|^3|^4|^5 ]]; then
              DIFF="Easy"
              EASY=$((EASY+1))
            elif [[ "$NAME" =~ ^6|^7|^8|^9|^10|^11|^12|^13 ]]; then
              DIFF="Medium"
              MEDIUM=$((MEDIUM+1))
            else
              DIFF="Hard"
              HARD=$((HARD+1))
            fi

            echo "| $TOTAL | $NAME | $DIFF | Java |" >> table.md
          done

          echo "{ \"schemaVersion\": 1, \"label\": \"Problems Solved\", \"message\": \"$TOTAL\", \"color\": \"brightgreen\" }" > badge-total.json
          echo "{ \"schemaVersion\": 1, \"label\": \"Easy\", \"message\": \"$EASY\", \"color\": \"success\" }" > badge-easy.json
          echo "{ \"schemaVersion\": 1, \"label\": \"Medium\", \"message\": \"$MEDIUM\", \"color\": \"orange\" }" > badge-medium.json
          echo "{ \"schemaVersion\": 1, \"label\": \"Hard\", \"message\": \"$HARD\", \"color\": \"red\" }" > badge-hard.json

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update LeetCode stats" || exit 0
          git push
